### ISSUE TITLE
Uncaught exception crashes Node-RED

### ISSUE THREAD

**Issue by crenz** [ppatierno/node-red-contrib-rhea#12]
I'm trying to use _node-red-contrib-rhea_ with Eclipse Hono. In that process, I accidentally connected a send node to the Qpid dispatcher (port 15672). The Qpid dispatcher rejects the link, resulting in an exception that stops Node-RED completely. Unfortunately, this also prevents Node-RED from starting ever again, until either the flows file gets deleted or the send node is edited out of the flows file.

Is there any chance you could catch this exception when establishing the link, and sending it to debug output instead?

```
3 Feb 23:09:35 - [info] Starting flows
3 Feb 23:09:35 - [info] Started flows
3 Feb 23:09:35 - [red] Uncaught Exception:
3 Feb 23:09:35 - Error: link disallowed by local policy
    at Sender.link.on_detach (/usr/src/node-red/node_modules/rhea/lib/link.js:146:86)
    at Session.on_detach (/usr/src/node-red/node_modules/rhea/lib/session.js:608:27)
    at Connection.(anonymous function) [as on_detach] (/usr/src/node-red/node_modules/rhea/lib/connection.js:635:30)
    at c.dispatch (/usr/src/node-red/node_modules/rhea/lib/types.js:902:33)
    at Transport.read (/usr/src/node-red/node_modules/rhea/lib/transport.js:95:36)
    at SaslClient.read (/usr/src/node-red/node_modules/rhea/lib/sasl.js:243:26)
    at Connection.input (/usr/src/node-red/node_modules/rhea/lib/connection.js:413:35)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```

**Comment by ppatierno** [comment]
Closed on behalf of 8cd1a4937c8fcc2b0e417e77490ee7bd2984a7b2
