### ISSUE TITLE
TypeError: Cannot assign to read only property 'writeQueueSize' of object '#<TCP>'

### ISSUE THREAD

**Issue by GTerryLiu** [ppatierno/node-red-contrib-rhea#21]
I used amqp sender to send messages to rabbitmq. And I found that rabbitmq received the message. But on node-red console, the server stopped by errors. The error message is as below.
TypeError: Cannot assign to read only property 'writeQueueSize' of object '#&lt;TCP&gt;'
     at _clone (/srv/node-red/node_modules/clone/clone.js:162:16)
     at _clone (/srv/node-red/node_modules/clone/clone.js:162:18)
     at _clone (/srv/node-red/node_modules/clone/clone.js:162:18)
......

Node.js version: v10.16.3
Node-RED version: v1.0.2

Can somebody help?

**Comment by pratham2003** [comment]
I'm getting a similar error too when using node-red chatbot.
But the error is probably related to `redUtil.cloneMessage` ?

**Comment by roxannems** [comment]
Hi there! I've run into the same error on Node-RED version 1.0.2. I haven't found a solution for this on that version, however, upgrading node-red to v1.1.2 fixed it for me. Hope it helps.

**Comment by GTerryLiu** [comment]
> Hi there! I've run into the same error on Node-RED version 1.0.2. I haven't found a solution for this on that version, however, upgrading node-red to v1.1.2 fixed it for me. Hope it helps.

Thanks. I just changed codes on v1.0.2 and the error disappeared. What I changed is adding a line as following.
----------------------
add "delete msg.delivery.link" before line 282 in rhea.js
----------------------
I know that it was just a solution temporarily. I think you just bring a regular solution.
